name: impromptustudio
favicon: null
layout_spectrum: 0
typography_spectrum: 0.54456
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ceb34e'
    - '#e8670b'
    - '#4bd4d9'
    - '#d82801'
    - '#241a0f'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
