name: impromptustudio
favicon: null
layout_spectrum: 1
typography_spectrum: 0.54456
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3cadff'
    - '#ffffff'
    - '#000000'
    - '#1d557e'
    - '#b7e1ff'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
