name: impromptustudio
favicon: null
layout_spectrum: 0.9733718796633184
typography_spectrum: 0.7363757682032883
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.08922544308006763
  lightness: 0.8056614070665091
  saturation: 0.8724774888250977
  rhythmicContrast: 0.8023898731917143
purpose: []
