name: impromptustudio
favicon: null
layout_spectrum: 0
typography_spectrum: 0.54456
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5
  lightness: 0.8056614070665091
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
